export const GET_PRODUCTS = "GET_PRODUCTS";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES"
export const FETCH_BY_CATEGORY = "FETCH_BY_CATEGORY";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";